apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "exec"
    

  name: "vocbench"
  labels:
    app: "vocbench"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "vocbench-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "vocbench"
        app.kubernetes.io/component: "vocbench-${env}"
        app.kubernetes.io/instance: "vocbench-${env}"
        app.kubernetes.io/name: "vocbench"
        app.kubernetes.io/part-of: "vocbench"
        app.openshift.io/runtime: "vocbench"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "vocbench"
        env: ${env}
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
        alpha.image.policy.openshift.io/resolve-names: '*'
        image.openshift.io/triggers: >-
          [{"from":{"kind":"ImageStreamTag","name":"vocbench:${env}"},"fieldPath":"spec.template.spec.containers[?(@.name==\"vocbench-${env}\")].image"}]
      name: "vocbench-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "vocbench"
        app.kubernetes.io/component: "vocbench-${env}"
        app.kubernetes.io/instance: "vocbench-${env}"
        app.kubernetes.io/name: "vocbench"
        app.kubernetes.io/part-of: "vocbench"
        app.openshift.io/runtime: "vocbench"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "vocbench"
          env: ${env}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "vocbench"
            deploymentconfig: "vocbench-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          volumes:
            - name: vocbench-${env}
              persistentVolumeClaim:
                claimName: vocbench-${env}
          containers:
            - name: "vocbench-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: vocbench-${env}
                  mountPath: /opt/vocbench3/data
              terminationMessagePolicy: File
              image: >-
                image-registry.openshift-image-registry.svc:5000/metadata-mgm/vocbench:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "1979"
